# Simple workflow for deploying static content to GitHub Pages
name: Despliegue pagina estatica a Azure

on:
  # Runs on pushes targeting the default branch
  push:
    branches: 
        - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: '.'
      - name: Deploy to Azure
        id: deploy-to-webapp
        uses: actions/webapps-deploy@v2
        with:
          app-name: 'teo-page'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_58774014503B452FBC3C9086B8259D63 }}
          package: .
